name: OWASP ZAP Integration with github actionss
on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # docker image of the zap proxy
          docker_name: 'owasp/zap2docker-stable'
          # The target website where the test will run
          target: 'http://testphp.vulnweb.com/'
          # passing the rules file name
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'